### ISSUE TITLE
I am trying to save new property on my server.. but I have been in trouble seriously..

### ISSUE THREAD

**Issue by calebyk** [etewiah/property_web_builder_admin#1]
// propertyResource: {},
    actions: {
    createPropertyResource: function() {
      var propertyResource = this.get("resourceObject");
      var self = this;

      function transitionToPost(propertyResource) {
        self.get('router').transitionTo('properties.editar',  propertyResource.id);
      }

      function failure(reason) {
        // handle the error
      }
        propertyResource.save().then(transitionToPost).catch(failure);
      }
    }

"Error: Assertion Failed: '(unknown mixin)' does not appear to be an ember-data model
    at new EmberError (http://localhost:4200/assets/vendor.js:24258:25)
    at Object.assert (http://localhost:4200/assets/vendor.js:24501:15)
    at Class._modelFactoryFor (http://localhost:4200/assets/vendor.js:113899:42)
    at Class._modelFor (http://localhost:4200/assets/vendor.js:113878:29)
    at Class.modelFor (http://localhost:4200/assets/vendor.js:113870:17)
    at Function.typeForRelationship (http://localhost:4200/assets/vendor.js:104499:34)
    at Function._findInverseFor (http://localhost:4200/assets/vendor.js:104559:28)
    at Function.inverseFor (http://localhost:4200/assets/vendor.js:104551:38)
    at Function.determineRelationshipType (http://localhost:4200/assets/vendor.js:104843:24)
    at Class._shouldSerializeHasMany (http://localhost:4200/assets/vendor.js:119601:44)"

when I traced it with a debugger, I found it couldn't pass through payload part and jumped to callback.. and throw that error, even couldn't request server api..

thank you in advance..

**Comment by etewiah** [comment]
Hi @calebyk, thanks for trying out PropertyWebBuilder.  Can you point me to the exact line of code in your github repo so I can understand better what is going on?

By the way,  I will soon replace this ember app with a vue js app.  If you are interested in helping me with this, let me know.  It will be a great chance to understand the internals of the admin panel.

**Comment by calebyk** [comment]
Wow, thank you for invite me to the work..
I can join in a vue js app..

The issue is that I am trying to input a new property or edit a property..

I am using the same code with pwb admin code,
But ember-cli version is 2.18

Let me share it with email soon

**Comment by calebyk** [comment]
https://github.com/calebyk/space

it is my github repo for the testing codes.. i am trying to make new
propery into back end api app

thank you..

**Comment by calebyk** [comment]
Hello,

How are you?

I am struggling for few days even a week to solve the issue..
I am trying to edit property admin saving function..

But I cannot save.. I think, I am stuck at the point of
Property Edit General Tab,
and saving action..

*resourceObject.save()..*

can you help me?

thank you..


triggerReset: function() {
      this.set("changedFields", []);
      this.set("hasChanged", false);
      this.set("fieldsWithErrors", []);
      this.set("hasErrors", false);
      this.set("resetTrigger", this.get("resetTrigger") + 1);
               // debugger;
               console.log(this.get("resetTrigger"));
    },
    // TODO - ensure below is being used correctly
    saveResourceObject: function() {
      var resourceObject = this.get("resourceObject");
      var self = this;

      function success(result) {
        // triggerReset is an action in TabWithForm
        self.send("triggerReset");
                       // debugger;
      }

      function failure(reason) {
        // handle the error
        //var errorMessage = "Sorry, there has been an error.";
        //if (error.responseJSON && error.responseJSON.errors) {
        //   errorMessage = error.responseJSON.errors[0];
        //}
        //this.set('serverError', errorMessage);
      }

      if (typeof resourceObject.store === "object") {
        // for propertyResource which uses ember data:
        //console.log(resourceObject);
        debugger;
        *resourceObject.save().then(success).catch(failure);*
*                //debugger;*
      } else {
        debugger;

        resourceObject.save(success, failure);

      }
    },

**Comment by etewiah** [comment]
Hello there, for me to be able to help you will have to give me some good information.  What command did you run?  What exactly is the error?  Point me to the line of code that is generating the error?   Is everything else working okay?  The more information you provide the more I can help.

If you prefer to talk via skype, my username there is tewiii

**Comment by calebyk** [comment]
Very many thanks!!
What time is good for you doing skype?

Here is new york time zone.

**Comment by calebyk** [comment]
the details of discussing today.. ^^
